name: Java CI/CD with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test with Gradle
      run: ./gradlew test
      
    - name: Install XML processing tools
      run: sudo apt-get install -y libxml2-utils

    - name: Generate Jacoco Test Coverage Report
      run: ./gradlew jacocoTestReport
    
    - name: List contents of the Jacoco report directory
      run: ls -al build/reports/jacoco/test/
    
    - name: Upload Jacoco Report Directory
      uses: actions/upload-artifact@v2
      with:
        name: Jacoco Report
        path: build/reports/jacoco/test/

    - name: Debug - Show jacocoTestReport.xml content
      run: cat build/reports/jacoco/test/jacocoTestReport.xml

    - name: Calculate Test Coverage
      run: |
        covered=$(xmllint --xpath 'sum(//counter[@type="LINE"]/@covered)' build/reports/jacoco/test/jacocoTestReport.xml)
        total=$(xmllint --xpath 'sum(//counter[@type="LINE"]/@covered + //counter[@type="LINE"]/@missed)' build/reports/jacoco/test/jacocoTestReport.xml)
        coverage=$(echo "scale=2; $covered / $total" | bc)
        echo "Overall Coverage: $coverage"
        required_coverage=0.90
        comparison=$(echo "$coverage >= $required_coverage" | bc -l)
        echo "Coverage Comparison (1 if true, 0 if false): $comparison"
        if [ "$comparison" -eq "0" ]; then
          echo "Code coverage is less than required $required_coverage (actual: $coverage)"
          exit 1
        fi
  
    - name: Package (only for master branch)
      if: github.ref == 'refs/heads/master'
      run: ./gradlew assemble

    - name: Upload Artifacts (only for master branch)
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: build/libs/*.jar
