name: Java CI/CD with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean
      run: ./gradlew clean

    - name: Build
      run: ./gradlew build

    - name: Test
      run: ./gradlew test

    - name: Check for Test Coverage
      run: ./gradlew check

    - name: Package
      run: ./gradlew assemble

    - name: Deploy to My CSUDH Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Your csudh.pem content should be here
      run: |
        # Install SSH client
        sudo apt-get update
        sudo apt-get install -y openssh-client
        # Start SSH agent
        eval $(ssh-agent -s)
        # Create SSH directory and give it the right permissions
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        # Add the SSH private key from the GitHub secrets
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/csudh.pem
        chmod 600 ~/.ssh/csudh.pem
        # Use SSH to execute deployment script on EC2
        ssh -o "StrictHostKeyChecking=no" -i ~/.ssh/csudh.pem ec2-user@54.156.126.16 'bash -s' < deploy_script.sh
        # Note: deploy_script.sh should be a script that resides in your repository and contains the deployment commands.

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: build/libs/*.jar
