name: Java CI/CD with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean
      run: ./gradlew clean

    - name: Build
      run: ./gradlew build

    - name: Test
      run: ./gradlew test

    - name: Check for 100% Test Coverage
      run: |
        if grep -q 'missed="[^0]' build/reports/jacoco/test/jacocoTestReport.xml; then
          echo "Code coverage is less than 100%"
          exit 1
        else
          echo "Code coverage is 100%"
        fi

    - name: Package
      run: ./gradlew assemble

    - name: Deploy (optional)
      run: ./gradlew deploy

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: build/libs/*.jar
