name: Java CI/CD with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test with Gradle
      run: ./gradlew test

    - name: Generate Jacoco Test Coverage Report
      run: ./gradlew jacocoTestReport
    
    - name: Verify Test Coverage
      run: |
        coverage=$(grep 'line-rate' build/reports/jacoco/test/jacocoTestReport.xml | grep -o 'line-rate="[^"]*' | grep -o '[0-9.]*')
        if [ $(echo "$coverage < 1" | bc) -ne 0 ]; then
          echo "Code coverage is less than 100%"
          exit 1
        fi
    
    - name: Upload Jacoco Test Coverage Report
      uses: actions/upload-artifact@v2
      with:
        name: Jacoco Test Coverage Report
        path: build/reports/jacoco/test/jacocoTestReport.xml
              
    - name: Package (only for master branch)
      if: github.ref == 'refs/heads/master'
      run: ./gradlew assemble

    - name: Upload Artifacts (only for master branch)
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: build/libs/*.jar
