name: Java CI/CD with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Test with Gradle
      run: ./gradlew test

    - name: Generate Jacoco Test Coverage Report
      run: ./gradlew jacocoTestReport
    
    - name: List contents of the Jacoco report directory
      run: ls -al build/reports/jacoco/test/
    
    - name: Upload Jacoco Report Directory
      uses: actions/upload-artifact@v2
      with:
        name: Jacoco Report
        path: build/reports/jacoco/test/
    
    - name: Verify Test Coverage
      run: |
        coverage=$(grep 'line-rate' build/reports/jacoco/test/jacocoTestReport.xml | grep -o 'line-rate="[^"]*' | grep -o '[0-9.]*' | awk '{sum+=$1; count++} END {print sum/count}')
        echo "Overall Coverage: $coverage"
        required_coverage=0.90
        comparison=$(echo "$coverage >= $required_coverage" | bc)
        echo "Coverage Comparison (1 if true, 0 if false): $comparison"
        if [ "$comparison" -eq "0" ]; then
          echo "Code coverage is less than required $required_coverage (actual: $coverage)"
          exit 1
        fi
              
    - name: Package (only for master branch)
      if: github.ref == 'refs/heads/master'
      run: ./gradlew assemble

    - name: Upload Artifacts (only for master branch)
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: build/libs/*.jar
