name: Java CI/CD with Gradle

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-test-coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean
      run: ./gradlew clean

    - name: Build
      run: ./gradlew build

    - name: Test
      run: ./gradlew test

    - name: Check for Test Coverage
      run: ./gradlew check

    - name: Package
      run: ./gradlew assemble

    - name: Deploy to My CSUDH Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Your csudh.pem content should be here
      - name: Deploy to My CSUDH Server
  env:
    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  run: |
    # Install SSH client
    sudo apt-get update
    sudo apt-get install -y openssh-client
    # Start SSH agent
    eval $(ssh-agent -s)
    # Add the SSH private key from the GitHub secrets
    echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    # Disable host key checking for the initial connection
    ssh-keyscan 54.156.126.16 >> ~/.ssh/known_hosts
    # Use SSH to execute the deployment script on the EC2 instance
    scp -i ~/.ssh/deployment_key deploy_script.sh ec2-user@54.156.126.16:/tmp/
    ssh -i ~/.ssh/deployment_key ec2-user@54.156.126.16 'bash /tmp/deploy_script.sh'

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: packaged-jar
        path: build/libs/*.jar
